### ISSUE TITLE
*DBOOT and Shift+BREAK broken in Pi1MHz version of 1.57

### ISSUE THREAD

**Issue by mincebert** [hoglet67/MMFS#38] opened 2024-05-23 08:45 UTC
I'm using MMFS 1.57 (commit 22d5e74) built locally and am using the Pi1MHz variant of MMFSv1.  When I try to `*DBOOT 116` a disc, I get the error `Wrong card!` and then the card no longer works (I can't do `*.` or `*DCAT`, etc.) — I need a Ctrl+Break to get things back (just Break doesn't work).  The same thing occurs if I `*DIN 116` a disc and push Shift+Break.

If, however, I just do `*DIN 116` and then (say) `*EXEC !BOOT` to load it up, it's fine, which makes me think the card and `BEEB.MMB` is basically OK (i.e. the file isn't fragmented).

This seems to only affect the Pi1MHz version and not the User Port Turbo version.

This seems to have broken somewhere around 1.56 but I'm not clear where — a version Dominic published on StarDot a couple of weeks ago of 1.56 was also broken, but I have a version 1.56 lying about from somewhere that, if I revert to that, is working (I assume it's a slightly different build).

This affects both the Model B and Electron.

**Comment by hoglet67** [comment] 2024-05-23 10:31
Could you possibly build/test the version on the dev branch?

**Comment by mincebert** [comment] 2024-05-23 21:52
I didn't notice the dev branch!  Anyway, I've checked out the latest commit 26d0b38 (which is just after 1.58) and I'm getting the same issue with that, too — `*DBOOT` and Shift+Break fail but `*DIN` followed by `*EXEC` is fine.

I've only tested it on the Electron but I assume this affects the BBC versions too.  I'm using `build/MMFS/1/ESWMMFS.rom`.

**Comment by hoglet67** [comment] 2024-05-26 15:47
Just to say I've replicated this, and it's caused by this commit: 714f811

I think the minimal fix for this is for the Pi1MHz specific version of GetCIDCRC to return a constant value in A and Y.

I'll fix this in dev now.

**Comment by hoglet67** [comment] 2024-05-26 16:06
Robert,

This is now fixed on dev.

FYI, The MMFS code base is undergoing a lot of change at the moment, as Dominic continues his work to reclaim more free space for new features.  I think we are going to continue working on the dev branch for a while longer.

I'll probably not push any more formal releases on github (and indeed I've just got rid of the 1.56 and 1.57 pre-releases as they were rather broken).

Any testing you can do on the latest code in the dev branch is most welcome.

It's currently on commit 124fbf0

Don't be surprised if you find other thimgs broken.

**Comment by mincebert** [comment] 2024-05-28 22:15
Thanks for fixing that — it looks like that's resolved now as I can boot discs again.

I'll happily keep testing things and I think I've found another bug, perhaps with OSBGPB, as `*BUILD` seems to write a corrupted file.  This is with the plain MMFS Turbo version; I've not tried the others.  I notice @dp111 has other stuff going on in an OSGBPB branch, though — should I ignore those and wait for you to merge them in, or report them to him?

**Comment by hoglet67** [comment] 2024-05-29 10:24
Please do create a bug report for the *BUILD issue. It's better to get thiese fixed sooner rather than later.

Dominic's OSGBPB branch is badly names, as it's now a general optimization branch. I'm periodically merging this into my dev branch and testing. I did that last on 22nd May. I'll probably do it again this week.

Dave

**Comment by dp111** [comment] 2024-05-29 10:42
Yeah, my branch name isn't very well named as I started out with one task
and ran out of space.

I don't know of any issues on my branch currently, so please do let me know.

I have a local branch which has code to do fragment detection, but I have
currently run out of space. I know where I will find it, but I have a
number of steps to take before I have the space free.

**Comment by hoglet67** [comment] 2024-07-16 10:07
Just coming back to this....

I've merged all of Dominic's space changing fixes (i.e. his OSGBPB branch) into my dev branch.

Re: the *BUILD issue, I've replicated this and fixed it here: 3c1dc541

I'm going to do a bit more testing, then make a MMFS 1.59 release.

**Closed** 2024-07-16 10:35 UTC
