### ISSUE TITLE
Acheton/Master MultiOS/MMFS Not Loading

### ISSUE THREAD

**Issue by acheton1984** [hoglet67/MMFS#33] opened 2023-11-11 18:19 UTC
Master with MultiOS set to any OS version with MMFS 1.55 will not load either Acornsoft or Topologica’s versions of Acheton.

Using MMFS 1.55 with the ROMS arranged so the Master version runs on MOS 3.x and the Model B version on 1.2/2.0. In OS 1.2/2.0 config, I *KILL 14 (DFS) (with Advanced ROM Manager) to keep page at &1900, otherwise "No room" errors creep in.

The disc image boots, the loader / introduction screen loads, but the game itself never loads

OS 1.2 / 2.0 with either Acornsoft or Topoligica, it says “Insert database disc”, then “Mismatch” after pressing SPACE
MOS 3.2 with either hangs after pressing SPACE
MOS 3.5 instead gives “Bad string”

The BEEB.MMB is the latest from the “A new MENU system for MMC/Gotek” thread.

A fresh download of Acornsoft Acheton from bbcmicro does the same on physical hardware with MMFS, but works happily in MAME (emulating a Master 3.20) as a DFS disc image without MMFS

**Comment by hoglet67** [comment] 2023-11-12 11:54
OK, I think this might be an easy one....

You just need to make sure any higher priority DFS ROM is disabled, otherwise it will intercept OSWORD 7F calls which Acheton uses for data access.

On the Master, *UNPLUG 9 then Ctrl-BREAK.

On the BBC, you will need to use a ROM Manager to do this.

> In OS 1.2 config, I *KILL 14 (DFS) (with Advanced ROM Manager) to keep page at &1900

I'm not sure why this didn't work - can you list the ROMs that are present?

I've tried three versions:
- the Acornsoft version from the BBC Micro games archive website
- the Topologika version from the BBC Micro games archive website
- version on the STH MMB archive

Dave

**Comment by acheton1984** [comment] 2023-11-12 12:26
No joy, I'm afraid. All (Acornsoft) result in "Mismatch" after pressing SPACE to read the database disc.

I tried doing a spool of *fx0, *roms, *kill [dfs on OS1.2/2.0], *roms to show you - but not everything has appeared in the spool file! Anyway, OS1.2 and 2.0 are the same as each other. 3.2 and 3.5 are the same as each other. NB: I did do a Ctrl-Break!

[1.20.txt](https://github.com/hoglet67/MMFS/files/13327962/1.20.txt)
[2.00.txt](https://github.com/hoglet67/MMFS/files/13327963/2.00.txt)
[3.20.txt](https://github.com/hoglet67/MMFS/files/13327964/3.20.txt)
[3.50.txt](https://github.com/hoglet67/MMFS/files/13327965/3.50.txt)

The "Model B" MMFS is on the motherboard in ROM slot 8 - and unplugged for 3.x. The "Master" MMFS is in a RAM/ROM catridge and I switch it out when using the B/B+ OSes

**Comment by hoglet67** [comment] 2023-11-12 13:04
Right, lets focus on one configuration: MOS 3.20.

I've tried my best to replicate your setup:
![capture1](https://github.com/hoglet67/MMFS/assets/1951463/a5595c25-fe5a-4c4f-99c7-a99d1befad24)
![capture2](https://github.com/hoglet67/MMFS/assets/1951463/3c45e82d-dad5-44e6-a91f-6bf78c8e1a9a)

With this setup Acheton works for me when running from:
- the original STH BEEB.MMB file
- the disk images downloaded from the BBC Micro Games Archive

After some head scratching, I re-read your original post, and it seems you are using Tricky's MMB Menu.  I've never used that, but I've just downloaded a copy and I can reproduce the failure:
![capture3](https://github.com/hoglet67/MMFS/assets/1951463/fff26f4b-78f6-42f2-b72d-2a73cb6ca0cc)
![capture4](https://github.com/hoglet67/MMFS/assets/1951463/8f6cbf26-ae1d-436b-9e21-3f6e9d648a04)

So I think this is a issue in Tricky's archive, not MMFS.

Specifically, if he has just copied the Acheton files, then that will break the game, because the game uses OSWORD 7F to access disk blocks directly.

Dave

**Comment by hoglet67** [comment] 2023-11-12 13:07
> A fresh download of Acornsoft Acheton from bbcmicro does the same on physical hardware with MMFS, but works happily in MAME (emulating a Master 3.20) as a DFS disc image without MMFS

Can you attach that image here please.

**Comment by acheton1984** [comment] 2023-11-12 13:28
Success - due to a combination of things.

Here's the link to Acheton disc image from bbcmicro [http://bbcmicro.co.uk/game.php?id=2021](url) and the image itself 
[Disc999-ACHETONFin.ssd.zip](https://github.com/hoglet67/MMFS/files/13328098/Disc999-ACHETONFin.ssd.zip)

*DBOOT ACHETON will hang when trying to load the database file UNLESS DFS is unplugged.

So, for MOS 3.20, the fix is: use the disc image from bbcmicro (not Tricky's archive) AND unplug DFS

Thanks for your help!

**Comment by hoglet67** [comment] 2023-11-12 14:22
All sorted, closing....

**Closed as completed by hoglet67** 2023-11-12 14:22 UTC
